name: GeoSuggester
author: panaghia
category: Forms
tags: [geocoding, autocomplete, input, form]
demo: http://geosuggester.panaghia.it/demo/
docs: https://github.com/panaghia/GeoSuggester/wiki/Documentation
current: 0.5